/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instrumentos.presentacion.tipoinstrumento;
import instrumentos.entidades.TipoInstrumento;
import instrumentos.presentacion.Application;
import java.util.Observable;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class TipoInstrumentoView extends javax.swing.JInternalFrame implements java.util.Observer{
    TipoInstrumentoModel model;
    TipoInstrumentoController controller;
    
    public TipoInstrumentoView() {
        initComponents();
    }

    public JTextField getCodigo_tf() {
        return codigo_tf;
    }

    public void setCodigo_tf(JTextField codigo_tf) {
        this.codigo_tf = codigo_tf;
    }

    public JTextField getNombre_tf() {
        return nombre_tf;
    }
    

    public void setNombre_tf(JTextField nombre_tf) {
        this.nombre_tf = nombre_tf;
    }

    public JTextField getUnidad_tf() {
        return unidad_tf;
    }

    public void setUnidad_tf(JTextField unidad_tf) {
        this.unidad_tf = unidad_tf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigo_lbl = new javax.swing.JLabel();
        codigo_tf = new javax.swing.JTextField();
        nombre_lbl = new javax.swing.JLabel();
        nombre_tf = new javax.swing.JTextField();
        unidad_lbl = new javax.swing.JLabel();
        unidad_tf = new javax.swing.JTextField();
        save_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();

        setClosable(true);
        setTitle("TIPO INSTRUMENTO");
        setMaximumSize(new java.awt.Dimension(300, 235));
        setMinimumSize(new java.awt.Dimension(300, 235));

        codigo_lbl.setText("Codigo");

        nombre_lbl.setText("Nombre");

        unidad_lbl.setText("Unidad");

        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/save.png"))); // NOI18N
        save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_buttonActionPerformed(evt);
            }
        });

        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/cancel.png"))); // NOI18N
        cancel_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancel_buttonMouseClicked(evt);
            }
        });
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidad_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codigo_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombre_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(codigo_tf)
                    .addComponent(unidad_tf))
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(save_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codigo_lbl)
                    .addComponent(codigo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombre_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(nombre_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unidad_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(unidad_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(save_button)
                    .addComponent(cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancel_buttonMouseClicked
       this.setVisible(false);
    }//GEN-LAST:event_cancel_buttonMouseClicked

    private void save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_buttonActionPerformed
        try{
        this.controller.guardar();
        }catch (Exception e) {
            //Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_buttonActionPerformed

    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed
       try{
        this.setVisible(false);
       }catch (Exception e) {
            //Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancel_buttonActionPerformed

    public TipoInstrumentoModel getModel() {
        return model;
    }

    public TipoInstrumentoController getController() {
        return controller;
    }

    public void setModel(TipoInstrumentoModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public void setController(TipoInstrumentoController controller) {
        this.controller = controller;
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel codigo_lbl;
    public javax.swing.JTextField codigo_tf;
    private javax.swing.JLabel nombre_lbl;
    public javax.swing.JTextField nombre_tf;
    private javax.swing.JButton save_button;
    private javax.swing.JLabel unidad_lbl;
    public javax.swing.JTextField unidad_tf;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        TipoInstrumento tipoInstrumentoCurrent=model.getCurrent();
        this.codigo_tf.setEnabled(model.getModo()==Application.MODO_AGREGAR);
        codigo_tf.setText(tipoInstrumentoCurrent.getCodigo());
        if (model.getErrores().get("id")!=null){
            codigo_lbl.setBorder(Application.BORDER_ERROR);
            codigo_lbl.setToolTipText(model.getErrores().get("codigo"));
        }
        else{
            codigo_lbl.setBorder(null);
            codigo_lbl.setToolTipText("");
        }
        nombre_tf.setText(tipoInstrumentoCurrent.getNombre());
        if (model.getErrores().get("nombre")!=null){
            nombre_tf.setBorder(Application.BORDER_ERROR);
            nombre_tf.setToolTipText(model.getErrores().get("nombre"));
        }
        else{
           nombre_tf.setBorder(null);
           nombre_tf.setToolTipText("");
        }
        unidad_tf.setText(tipoInstrumentoCurrent.getUnidad());
        if (model.getErrores().get("unidad")!=null){
            unidad_tf.setBorder(Application.BORDER_ERROR);
            unidad_tf.setToolTipText(model.getErrores().get("unidad"));
        }
        else{
           unidad_tf.setBorder(null);
           unidad_tf.setToolTipText("");
        }
        this.validate();
        if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
