
package instrumentos.presentacion.tipoinstrumento;

import instrumentos.presentacion.Application;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class TipoInstrumentosView extends javax.swing.JInternalFrame implements java.util.Observer{
    TipoInstrumentosController controller;
    TipoInstrumentosModel model;
    public boolean signal = false;
    public TipoInstrumentosView() {
        initComponents();
    }

    public TipoInstrumentosController getController() {
        return controller;
    }

    public void setController(TipoInstrumentosController controller) {
        this.controller = controller;
    }

    public TipoInstrumentosModel getModel() {
        return model;
    }

    public void setModel(TipoInstrumentosModel model) {
        this.model = model;
        model.addObserver(this);
    }

    public JTextField getCodigo_tf() {
        return codigo_tf;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        codigo_lbl = new javax.swing.JLabel();
        codigo_tf = new javax.swing.JTextField();
        search_button = new javax.swing.JButton();
        add_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tiposInst_table = new javax.swing.JTable();
        jUpdateButton = new javax.swing.JButton();

        setClosable(true);
        setTitle("Tipos de Instrumento");
        setMaximumSize(new java.awt.Dimension(580, 455));
        setMinimumSize(new java.awt.Dimension(580, 455));

        codigo_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        codigo_lbl.setText("Codigo");

        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/search.png"))); // NOI18N
        search_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        search_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                search_buttonMouseClicked(evt);
            }
        });

        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/add.png"))); // NOI18N
        add_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_buttonMouseClicked(evt);
            }
        });

        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/delete.png"))); // NOI18N
        delete_button.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delete_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_buttonMouseClicked(evt);
            }
        });
        delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_buttonActionPerformed(evt);
            }
        });

        tiposInst_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tiposInst_table);

        jUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/Update.png"))); // NOI18N
        jUpdateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(codigo_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(codigo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(codigo_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(codigo_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(search_button, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(delete_button, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(add_button, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(181, 181, 181))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_buttonMouseClicked
       try{
        controller.preAgregar();
       }catch (Exception e) {
            //Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_add_buttonMouseClicked

    private void delete_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_buttonMouseClicked
        int row = this.tiposInst_table.getSelectedRow();
        
        if (row!=-1){
            int resp =  JOptionPane.showConfirmDialog(this, "Desea borrar?");
            if (resp== JOptionPane.YES_OPTION){
                try {
                    controller.borrar(row);
                } catch (Exception e) {
                   // Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_delete_buttonMouseClicked

    private void search_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_search_buttonMouseClicked
       try {
           if(codigo_tf.getText().isEmpty()){
           signal=true;
           controller.searchAll();
           }else{
           controller.buscar();
           }
        } catch (Exception e) {
           // Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_search_buttonMouseClicked

    private void delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_buttonActionPerformed
        int row = tiposInst_table.getSelectedRow();
        
        try {
            if(row>-1){
            int resp =  JOptionPane.showConfirmDialog(this, "Desea borrar?");
            if (resp== JOptionPane.YES_OPTION){    
            controller.borrar(row);}
            }
            else{}
            
            } catch (Exception e) {
            //Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
            }
        
    }//GEN-LAST:event_delete_buttonActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
         int row = tiposInst_table.getSelectedRow();
        try {
            controller.preUpdate(row);
        } catch (Exception e) {
           // Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jUpdateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel codigo_lbl;
    private javax.swing.JTextField codigo_tf;
    private javax.swing.JButton delete_button;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jUpdateButton;
    private javax.swing.JButton search_button;
    public javax.swing.JTable tiposInst_table;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        codigo_tf.setText(model.getFilter().getCodigo());
        if (model.getErrores().get("codigo_tf")!=null){
            codigo_lbl.setBorder(Application.BORDER_ERROR);
            codigo_lbl.setToolTipText(model.getErrores().get("codigo_tf"));
        }
        else{
            codigo_lbl.setBorder(null);
            codigo_lbl.setToolTipText("");
        }
        this.tiposInst_table.setModel(model.getTipoInstrumentos());
        this.revalidate();
        
       if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }    
    
    }
}
