/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package instrumentos.presentacion.instrumento;

import instrumentos.entidades.Instrumento;
import instrumentos.presentacion.Application;
import instrumentos.presentacion.tipoinstrumento.TipoInstrumentosView;
import java.util.ArrayList;
import java.util.Observable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Addiel
 */
public class InstrumentosView  extends JInternalFrame implements java.util.Observer {
    InstrumentosModel model;
    public InstrumentosController controller;
    InstrumentoController control; 
    public boolean signal = false;
    public int row =0;
    public InstrumentosModel getModel() {
       return model;
    }
     public InstrumentosController getController() {
        return controller;
    }
    public void setController(InstrumentosController controller){
        this.controller=controller;
    }
    public void setModel(InstrumentosModel model){
        this.model=model;
         model.addObserver(this);
    }
   
     public InstrumentosView() {
        initComponents();
    }

    public JTextField getJserie() {
        return Jserie;
    }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabInstrumentos = new javax.swing.JTable();
        Jserie = new javax.swing.JTextField();
        JnameLabel = new javax.swing.JLabel();
        Jsearch = new javax.swing.JButton();
        jAdd = new javax.swing.JButton();
        jErase = new javax.swing.JButton();
        jCheck = new javax.swing.JButton();
        jUpdate = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Instrumentos");
        setMaximumSize(new java.awt.Dimension(580, 455));
        setMinimumSize(new java.awt.Dimension(580, 455));

        jTabInstrumentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTabInstrumentos);

        JnameLabel.setText("Serie");

        Jsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/search.png"))); // NOI18N
        Jsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JsearchActionPerformed(evt);
            }
        });

        jAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/add.png"))); // NOI18N
        jAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAddMouseClicked(evt);
            }
        });
        jAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddActionPerformed(evt);
            }
        });

        jErase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/delete.png"))); // NOI18N
        jErase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jErase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEraseActionPerformed(evt);
            }
        });

        jCheck.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/icon_check.png"))); // NOI18N
        jCheck.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckActionPerformed(evt);
            }
        });

        jUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instrumentos/presentacion/icons/Update.png"))); // NOI18N
        jUpdate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(JnameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jserie, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(jErase, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JnameLabel))
                    .addComponent(Jsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jErase, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddActionPerformed
        try {
            controller.preAgregar();
        }catch (Exception e) {
            //Logger.getLogger(InstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAddActionPerformed

    private void jCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckActionPerformed
        try{ 
        row = this.jTabInstrumentos.getSelectedRow();  
        controller.searchCalibraciones(row);
        }catch (Exception e) {
            //Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
           
       
    }//GEN-LAST:event_jCheckActionPerformed
    
    private void jEraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEraseActionPerformed
          row = this.jTabInstrumentos.getSelectedRow();
            int resp =  JOptionPane.showConfirmDialog(this, "Desea borrar?");
            if (resp== JOptionPane.YES_OPTION){
                try {
                    controller.eliminar(row);
                } catch (Exception e) {
                    //Logger.getLogger(InstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
    }//GEN-LAST:event_jEraseActionPerformed

    private void JsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JsearchActionPerformed
        try {
           if(Jserie.getText().isEmpty()){
           controller.getAll();
           }else{
           controller.buscar();
           }
        } catch (Exception e) {
            //Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_JsearchActionPerformed

    private void jAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAddMouseClicked
        try{
         //Application.INSTRUMENTOVIEW.setLocation(this.jAdd.getLocationOnScreen());
         controller.preAgregar();
        }catch (Exception e) {
            //Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jAddMouseClicked

    private void jUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateActionPerformed
        row = this.jTabInstrumentos.getSelectedRow();
        try{
        controller.preUpdate(row);
        signal = true;
        }
         catch (Exception e) {
           //Logger.getLogger(TipoInstrumentosView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jUpdateActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstrumentosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstrumentosView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JnameLabel;
    private javax.swing.JButton Jsearch;
    public javax.swing.JTextField Jserie;
    private javax.swing.JButton jAdd;
    public javax.swing.JButton jCheck;
    private javax.swing.JButton jErase;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabInstrumentos;
    private javax.swing.JButton jUpdate;
    // End of variables declaration//GEN-END:variables

     @Override
    public void update(Observable o, Object arg) {
        Jserie.setText(model.getFilter().getSerie());
        if (model.getErrores().get("Jserie")!=null){
            Jserie.setBorder(Application.BORDER_ERROR);
            Jserie.setToolTipText(model.getErrores().get("Jserie"));
        }
        else{
            Jserie.setBorder(null);
            Jserie.setToolTipText("");
        }
        jTabInstrumentos.setModel(model.getInstrumentos());
        this.revalidate();
        
       if (!model.getMensaje().equals("")){
            JOptionPane.showMessageDialog(this, model.getMensaje(), "",JOptionPane.INFORMATION_MESSAGE);
        }  
    }

   

    

}
