/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instrumentos.presentacion;

import javax.swing.JInternalFrame;

/**
 *
 * @author User
 */
public class AppView extends javax.swing.JFrame {

    /**
     * Creates new form AppView
     */
    public AppView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        instrumentoMenu = new javax.swing.JMenu();
        tipoInstrumentoMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(855, 500));
        setMinimumSize(new java.awt.Dimension(855, 500));

        jDesktopPane1.setLayout(new javax.swing.OverlayLayout(jDesktopPane1));

        instrumentoMenu.setText("Instrumento");
        instrumentoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instrumentoMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(instrumentoMenu);

        tipoInstrumentoMenu.setText("Tipo Instrumento");
        tipoInstrumentoMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tipoInstrumentoMenuMouseClicked(evt);
            }
        });
        jMenuBar1.add(tipoInstrumentoMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoInstrumentoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tipoInstrumentoMenuMouseClicked
      Application.TIPOINSTRUMENTOS_VIEW.setVisible(true);
      Application.TIPOINSTRUMENTOS_VIEW.toFront();
    }//GEN-LAST:event_tipoInstrumentoMenuMouseClicked

    private void instrumentoMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instrumentoMenuMouseClicked
        Application.INSTRUMENTOSVIEW.setVisible(true);
        Application.INSTRUMENTOVIEW.toFront();
    }//GEN-LAST:event_instrumentoMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppView().setVisible(true);
            }
        });
    }
      public void addInternalFrame(JInternalFrame f){
       this.jDesktopPane1.add(f);
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu instrumentoMenu;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu tipoInstrumentoMenu;
    // End of variables declaration//GEN-END:variables
}
